server:
  port: 9091
spring:
  data:
    mongodb:
      username: mongouser
      password: mongopass
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
