server:
  port: 9092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/changelog/changelog.xml
    enabled: true
